inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'test/dummy/**/*'

Metrics/BlockLength:
  Exclude:
    - 'wicked_pdf.gemspec'

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SafeNavigation:
  Enabled: false