language: ruby
git:
  depth: 1
  quiet: true
sudo: required
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - sudo apt-get update -qq
bundler_args: --verbose
before_script:
  - bundle list
  - sudo apt-get install -y wkhtmltopdf
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env: WKHTMLTOPDF_BIN=/usr/bin/wkhtmltopdf
script:
  - bundle exec rake

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile

rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
